/*
 * Copyright 2016 Orange.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.orange.osperf;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author Ayoub Bousselmi
 * @since August 2016
 */
public class OSInstance implements Runnable {

    //OpenStack control message sizes in Bytes
    //These values were calculated using a real OpenStack deployment. More 
    //details about this research can be found in our paper: "towards a 
    //massively distributed IaaS operating system: composition and evaluation of
    //OpenStack" submitted to IEEE CSCN conference (2016).
    //Note that at least 98% of the AMQP flow is generated by heartbeats
    //RPC size: CPU node heartbeats (0 VN 0 VM)
    private final int NOVA_OA         = 1890;
    private final int NOVA_OCAV       = 1890;
    private final int NOVA_SII        = 1000;
    private final int NOVA_REP        = 640;
    private final int NEUTRON_RS      = 1530;
    private final int NEUTRON_REP     = 200;
    //RPC size: Additional size (1 VN 1 VM)
    private final int NOVA_OA_ADD     = 110;
    private final int NOVA_OCAV_ADD   = 110;
    private final int NOVA_SII_ADD    = 210;
    private final int NOVA_REP_ADD    = 480;
    private final int NEUTRON_RS_ADD  = 0;
    private final int NEUTRON_REP_ADD = 40;
    
    //RPC rates
    
    //PerfTest arguments.
    //For more details about PerfTest, please visit:
    //https://www.rabbitmq.com/java-tools.html
    private String _h;     //connection uri
    private String _login; //rabbitmq login
    private String _passw; //rabbitmq password
    private String _f;     //message flag: mandatory or not
    private String _z;     //run duration in seconds (0 for illimited)
    
    //OpenStack simulation variables. 
    //For example: the number of compute nodes in a datacenter.
    private final int nbrCPUNodes;
    private final int nbrVNets;
    private final int nbrVMPerCPUNode;
    private final int nbrVMPerVNet;
    private final int nbrXVNet;

    //instance info variable
    private final String osInstanceName;
    private String instanceStartTime;
    
    private String[] args = null;
    /**
     * Constructor of an OpenStack instance.
     * @param osInstanceName the name of this instance
     * @param nbrCPUNodes the number of compute nodes
     * @param nbrVNets the number of virtual networks
     * @param nbrVMPerCPUNode the number of virtual machines per compute node
     * @param nbrVMPerVNet the number of virtual machine per virtual network
     * @param nbrXVNet the number of cross-POP virtual networks
     */
    public OSInstance(String osInstanceName, int nbrCPUNodes, int nbrVNets,
            int nbrVMPerCPUNode, int nbrVMPerVNet, int nbrXVNet) {
        initStartTime();
        this.osInstanceName  = osInstanceName;
        this.nbrCPUNodes     = nbrCPUNodes;
        this.nbrVNets        = nbrVNets;
        this.nbrVMPerCPUNode = nbrVMPerCPUNode;
        this.nbrVMPerVNet    = nbrVMPerVNet;
        this.nbrXVNet        = nbrXVNet;
        
        //construct RPC emulators arguments
        int[] configList = initConfigList();
    }
    
    /**
     * Do not use this method directly.<br> Use startInstance() instead.
     */
    @Override
    public void run() {
        System.out.println(instanceStartTime+" - starting \""+osInstanceName+
                "\" instance..");
        for (int i = 0; i < nbrCPUNodes; i++) {
            //launch a new node flow emulation test
            new RPCEmulator(args).startRPCEmulation();
        }
    }
    
    /**
     * Starts this OpenStack instance
     */
    public void startInstance() {
        new Thread(OSInstance.this).start();
    }

    /**
     * @return the instance start time
     */
    public String getInstanceStartTime() {
        return instanceStartTime;
    }
    
    private void initStartTime() {
        DateFormat df = new SimpleDateFormat("HH:mm:ss.SSS");
        Calendar cal = Calendar.getInstance();
        instanceStartTime = df.format(cal.getTime());
    }

    private int[] initConfigList() {
        int[] config = new int[6];
        
        config[0] = NOVA_OA + NOVA_OA_ADD * nbrVMPerCPUNode;
        config[1] = NOVA_OCAV + NOVA_OCAV_ADD * nbrVMPerCPUNode;
        config[2] = NOVA_SII + NOVA_SII_ADD * nbrVMPerCPUNode;
        config[3] = NEUTRON_RS + NEUTRON_RS_ADD * nbrVNets;
        config[4] = NOVA_REP + NOVA_REP_ADD * nbrVMPerCPUNode;
        config[5] = NEUTRON_REP + NEUTRON_REP_ADD * nbrVNets;

        return config;
    }
}
